apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
      - name: "main-ftps-port"
        port: 21
        targetPort: 21
      - name: "ftps-port1"
        port: 30000
        targetPort: 30000
      - name: "ftps-port2"
        port: 30001
        targetPort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          imagePullPolicy: Never
          image: d_ftps
          ports:
          - containerPort: 21
          - containerPort: 30000
          - containerPort: 30001